# -*- coding: utf-8 -*-

STATE_START = 1

STATE_EXPORT_CHOOSE_FORMAT = 1
STATE_EXPORT = 2

STATE_CHOOSE_EXECUTIVES = 2
STATE_CHOOSE_DOCUMENT = 3
STATE_CHOOSE_STAGE = 4

TRANSLATION_SERVICE_ID = CHAPTER_STATE_TRANSLATION = 1
EDITING_SERVICE_ID = CHAPTER_STATE_EDITING = 2
CHAPTER_STATE_FINAL_EDITING = 10
CHAPTER_STATE_PUBLISHED = 20

CHAPTER_STATUS_COMPLETED = 'completed'
CHAPTER_STATUS_IN_PROGRESS = 'inProgress'

CHAPTER_STAGE_NAMES = {
    CHAPTER_STATE_TRANSLATION: 'Перевод',
    CHAPTER_STATE_EDITING: 'Редактирование',
    CHAPTER_STATE_FINAL_EDITING: 'Чистовик',
    CHAPTER_STATE_PUBLISHED: 'Опубликовано',
}

PONY_CHUNK_LENGTH = 750
PONY_CHUNK_SENSITIVITY = 20
