# -*- coding: utf-8 -*-
LINKS = {
    '1.01': 'https://pactwebserial.wordpress.com/category/story/arc-1-bonds/1-01/',
    '1.02': 'https://pactwebserial.wordpress.com/category/story/arc-1-bonds/1-02/',
    '1.03': 'https://pactwebserial.wordpress.com/category/story/arc-1-bonds/1-03/',
    '1.04': 'https://pactwebserial.wordpress.com/category/story/arc-1-bonds/1-04/',
    '1.05': 'https://pactwebserial.wordpress.com/category/story/arc-1-bonds/1-05/',
    '1.06': 'https://pactwebserial.wordpress.com/category/story/arc-1-bonds/1-06/',
    '1.07': 'https://pactwebserial.wordpress.com/category/story/arc-1-bonds/1-07/',
    '1.x (Pages 1)': 'https://pactwebserial.wordpress.com/category/story/arc-1-bonds/1-x-pages-1/',

    '2.01': 'https://pactwebserial.wordpress.com/2014/01/18/damages-2-1/',
    '2.02': 'https://pactwebserial.wordpress.com/2014/01/21/damages-2-2/',
    '2.03': 'https://pactwebserial.wordpress.com/2014/01/25/damages-2-3-2/',
    '2.04': 'https://pactwebserial.wordpress.com/2014/01/28/damages-2-4/',
    '2.05': 'https://pactwebserial.wordpress.com/2014/02/01/damages-2-5/',
    '2.06': 'https://pactwebserial.wordpress.com/2014/02/04/damages-2-6/',
    '2.07': 'https://pactwebserial.wordpress.com/category/story/arc-2-damages/2-07/',
    '2.x (Pages 2)': 'https://pactwebserial.wordpress.com/category/story/arc-2-damages/2-x-pages-2/',
    '2.y (Histories)': 'https://pactwebserial.wordpress.com/category/story/arc-2-damages/2-y-histories/',

    '3.01': 'https://pactwebserial.wordpress.com/category/story/arc-3-breach/3-01/',
    '3.02': 'https://pactwebserial.wordpress.com/category/story/arc-3-breach/3-02/',
    '3.03': 'https://pactwebserial.wordpress.com/category/story/arc-3-breach/3-03/',
    '3.04': 'https://pactwebserial.wordpress.com/category/story/arc-3-breach/3-04/',
    '3.05': 'https://pactwebserial.wordpress.com/category/story/arc-3-breach/3-05/',
    '3.x (Histories)': 'https://pactwebserial.wordpress.com/category/story/arc-3-breach/3-x-histories/',

    '4.01': 'https://pactwebserial.wordpress.com/category/story/arc-4-collateral/4-01/',
    '4.02': 'https://pactwebserial.wordpress.com/category/story/arc-4-collateral/4-02/',
    '4.03': 'https://pactwebserial.wordpress.com/category/story/arc-4-collateral/4-03/',
    '4.04': 'https://pactwebserial.wordpress.com/category/story/arc-4-collateral/4-04/',
    '4.05': 'https://pactwebserial.wordpress.com/category/story/arc-4-collateral/4-05/',
    '4.06': 'https://pactwebserial.wordpress.com/category/story/arc-4-collateral/4-06/',
    '4.07': 'https://pactwebserial.wordpress.com/category/story/arc-4-collateral/4-07/',
    '4.08': 'https://pactwebserial.wordpress.com/category/story/arc-4-collateral/4-08/',
    '4.09': 'https://pactwebserial.wordpress.com/category/story/arc-4-collateral/4-09/',
    '4.10': 'https://pactwebserial.wordpress.com/category/story/arc-4-collateral/4-10/',
    '4.11': 'https://pactwebserial.wordpress.com/category/story/arc-4-collateral/4-11/',
    '4.12': 'https://pactwebserial.wordpress.com/category/story/arc-4-collateral/4-12/',
    '4.x (Pages 4)': 'https://pactwebserial.wordpress.com/category/story/arc-4-collateral/4-x-pages-4/',
}
