service: evan-bot

plugins:
  - serverless-python-requirements

custom:
  stage: "${opt:stage, env:SLS_STAGE, 'dev'}"
  log_level: "${env:LOG_LEVEL, 'INFO'}"

  pythonRequirements:
    dockerizePip: false
    slim: true

provider:
  name: aws
  # if you change the python runtime, lxml binaries need to be built.
  # see instructions here: https://stackoverflow.com/a/64749142/222173
  runtime: python3.8
  stage: ${self:custom.stage}
  region: eu-west-1
  environment:
    LOG_LEVEL: ${self:custom.log_level}
    TELEGRAM_TOKEN: ${env:TELEGRAM_TOKEN}
    CHATGPT_KEY: ${env:CHATGPT_KEY}
  stackTags:
    x-service: evan-bot
    x-stack: ${self:service}-${self:provider.stage}
  apiGateway:
    shouldStartNameWithService: true

package:
  patterns:
    - '!env/**'
    - '!node_modules/**'

functions:
  # for this webhook to work, you need to set it (once after deploy)
  # note the endpoint url, then:
  # curl --request POST \
  # --url https://api.telegram.org/bot{TELEGRAM_TOKEN}/setWebhook \
  # --header 'content-type: application/json' \
  # --data '{"url": "{ENDPOINT_URL}"}'
  webhook:
    handler: handlers/webhook.handler
    description: "Webhook handler"
    memorySize: 256
    timeout: 30
    events:
      - http:
          path: "${env:WEBHOOK_PATH, 'webhook'}"
          method: post
          cors: true

