# -*- coding: utf-8 -*-

START_HELLO = 'Привет! :) Напиши /help, если нужен список команд'
HELLO_THERE = "привет :)"
HELLO_REGEX = '(привет|здравст|здраст)'
OR_REGEX = "(.+?) или (.+?)[?]*$"
CHAPTER_REGEX = "глава\\s+(.+)$"
I_DONT_UNDERSTAND = "Я не понимаю"
SHIT_HAPPENS = "Что-то пошло не так"
NOTHING_FOUND = "Не могу найти что ты ищешь"
YOURE_MAKING_FUN_OF_ME = "Дурак что ли?"
DOCUMENT_LINK = "Ссылка на скачивание {0}: {1}"
YOU_HAVE_NO_POWER_OVER_ME = "У тебя нет власти надо мной"
NOBODY = "(никого)"
TRANSLATORS = "Переводчики"
EDITORS = "Редакторы"
DONE = "Готово!"
CLEARING_EXECUTIVES_DONE = "Я удалил из главы {0} {1} исполнителей"
OK_BYE = "Ладно, пока!"
ENTER_THE_DOCUMENT_NAME_ID_OR_CANCEL = "Напиши название/ID документа, или /cancel для выхода"
ALL_CHAPTERS = "Все главы"
ALL = "all"
ACTIVE_CHAPTERS = "Активные"
CHAPTERS_BEING_TRANSLATED = "Перевод"
CHAPTERS_BEING_EDITED = "Редактирование"
EXPORT_FORMAT_ORIGINAL_TEXT = "Оригинал txt"
EXPORT_FORMAT_TRANSLATION_TEXT = "Перевод txt"
EXPORT_FORMAT_PONY_HTML = "Подстрочник html"
